
server:
  port: 8085
spring:
  application:
    name: storage
#  main:
#    web-application-type: reactive
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/erm}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
      idle-timeout: 30000
      pool-name: HikariPool-1
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://erm-discovery-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: false

aws:
  access:
    key:
      id: ${AWS_ACCESS_KEY_ID:}
  secret:
    access:
      key: ${AWS_SECRET_ACCESS_KEY:}
  region: ${AWS_REGION:ap-south-1}
