spring:
  application:
    name: erm-api-gateway
  main:
    web-application-type: reactive
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/erm2}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:2116}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: HikariPool-1
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  cloud:
    gateway:
      gateway:
      routes:
        - id: erm-command-organization
          uri: lb://ERM-COMMAND-ORGANIZATION
          predicates:
            - Path=/org/**
          filters:
           - StripPrefix=1
        - id: erm-query-organization
          uri: lb://ERM-QUERY-ORGANIZATION
          predicates:
            - Path=/query-org/**
          filters:
           - StripPrefix=1
           
        - id: org-setup-command
          uri: lb://ORG-SETUP-COMMAND
          predicates:
            - Path=/org-setup/**
          filters:
           - StripPrefix=1
           
        - id: user-setup
          uri: lb://USER-SETUP
          predicates:
            - Path=/user/**
          filters:
           - StripPrefix=1
           
        - id: storage
          uri: lb://STORAGE
          predicates:
            - Path=/storage/**
          filters:
           - StripPrefix=1
           
        - id: erm
          uri: lb://ERM
          predicates:
           - Path=/erm/**
          filters:
           - StripPrefix=1
           

#      globalcors:
 #       cors-configurations:
   #       '[/**]': # Applies to all paths
     #       allowedOrigins: "http://localhost:3000"
       #     allowedMethods: GET, POST, PUT, DELETE, OPTIONS
        #    allowedHeaders: "*"
          #  allowCredentials: true

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          
         

#  cache:
#    type: redis
#  data:
#    redis:
#      host: localhost
#      port: 6379
#  logging:
#  level:
#    org.springframework.cache: DEBUG
            
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://erm-discovery-server:8761/eureka/}
      register-with-eureka: true
      fetch-registry: true
    server:
      enable-self-preservation: false

logging:
  level:
    org.springframework.security: DEBUG
allowed:
 origins: http://localhost:5173, http://localhost:5174, http://localhost:5175,http://localhost:4200

    
    
    

