spring:
  application:
    name: erm-command-organization
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/erm}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update

  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

# ✅ MOVE HERE
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://erm-discovery-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

  server:
    enable-self-preservation: false